In [1]:
%useLatestDescriptors
%use dataframe, kandy

// %use dataframe(1.0.0-Beta4n), kandy(0.8.3)

In [2]:
import util.Helpers

val helpers = Helpers()

In [3]:
fun queryByTimePeriodAndEntries(startYear: String, endYear: String, liftersPerWeightclass: Int) =
    """
SELECT
    pd.*
FROM
    powerlifting_data pd
        JOIN
    (
        SELECT
            meetname,
            date,
            weightclasskg,
            division,
            COUNT(*) AS lifter_count
        FROM
            powerlifting_data
        WHERE
            event = 'SBD' AND place != 'NS'
            AND date BETWEEN '$startYear-01-01' AND '$endYear-12-31'
            AND totalkg IS NOT NULL
        GROUP BY
            meetname, date, weightclasskg, division
        HAVING
            COUNT(*) >= $liftersPerWeightclass
    ) AS qualified_classes
    ON pd.meetname = qualified_classes.meetname
        AND pd.date = qualified_classes.date
        AND pd.weightclasskg = qualified_classes.weightclasskg
        AND pd.division = qualified_classes.division
WHERE
pd.event = 'SBD' AND pd.place != 'NS'
  AND pd.date BETWEEN '$startYear-01-01' AND '$endYear-12-31'
  AND pd.totalkg IS NOT NULL;
    """

In [4]:
import java.util.Date
import org.jetbrains.kotlinx.dataframe.annotations.*

// With @DataSchema, you get a generated typed API giving you compile-time type safety and IDE autocomplete.

@DataSchema
interface LifterData {
    val place: String
    val meetname: String
    val date: Date
    val event: String
    val weightclasskg: String?
    val entries: Int
    val division: String?
    val squat1kg: Double?
    val squat2kg: Double?
    val squat3kg: Double?
    val bench1kg: Double?
    val bench2kg: Double?
    val bench3kg: Double?
    val deadlift1kg: Double?
    val deadlift2kg: Double?
    val deadlift3kg: Double?
    val best3squatkg: Double?
    val best3benchkg: Double?
    val best3deadliftkg: Double?
    val totalkg: Double?
    val successfulLifts: Int
}

In [5]:
val query = queryByTimePeriodAndEntries(startYear = "2025", endYear = "2025", liftersPerWeightclass = 3)
val data: DataFrame<*> = helpers.fetchResults(query)

In [6]:
data.size()

47985 x 42

In [7]:
fun addNumberOfSuccessfulLifts(data: DataFrame<LifterData>, firstPlaceOnly: Boolean = true): DataFrame<LifterData> {

    val filteredDf = if (firstPlaceOnly) data.filter { it.place == "1" } else data

    return filteredDf.add("successfulLifts") {
        listOf(
            squat1kg, squat2kg, squat3kg,
            bench1kg, bench2kg, bench3kg,
            deadlift1kg, deadlift2kg, deadlift3kg
        ).count { it != null && it > 0.0 }
    }
        .filter { listOf(best3squatkg, best3benchkg, best3deadliftkg).all { it != null} }
        .groupBy { successfulLifts } // countPlot?
        .aggregate {
            count().into("count")
        }
        .filter { successfulLifts >= 3 }
        .sortBy { successfulLifts }
}

In [8]:
val winnersDataFrame = addNumberOfSuccessfulLifts(data.cast<LifterData>())

winnersDataFrame

successfulLifts,count
3,35
4,117
5,512
6,1284
7,2122
8,2546
9,1645

In [9]:
val barPlot = plot(winnersDataFrame) {

    bars {
        x(successfulLifts)
        y(count)
    }
}
barPlot
//barPlot.save("distribution-of-winners.svg")
//barPlot.save("distribution-of-winners.png")

In [10]:
val dfNoCount = data.filter { it.place == "1" }
    .add("successfulLifts") {
        listOf(
            squat1kg, squat2kg, squat3kg,
            bench1kg, bench2kg, bench3kg,
            deadlift1kg, deadlift2kg, deadlift3kg
        ).count { it != null && it > 0.0 }
    }
    .filter { listOf(best3squatkg, best3benchkg, best3deadliftkg).all { it != null} }

In [11]:
val countPlot = dfNoCount
    .filter { "successfulLifts"<Int>() in 3..9 }
    .plot {
        countPlot("successfulLifts")
    }

countPlot

In [12]:
val plotGridCount = plotGrid(
    listOf(barPlot, countPlot),
    nCol = 2
)

plotGridCount

In [13]:
kandyConfig.themeApplied = false

val plotWinners = winnersDataFrame.plot {

    bars {
        x(successfulLifts) {
            axis {
                name = "Successful Attempts"
                breaks(listOf(3, 4, 5, 6, 7, 8, 9), format = "d")
            }
        }
        y(count) {
            axis {
                name = "Number of Winners"
                breaks(listOf(500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000), format = "d")
            }
        }
        fillColor(count) {
            legend.type = LegendType.None
            scale = continuous(Color.hex("#dd4560")..Color.hex("#7e52ff"))
        }
        borderLine {
            color = Color.hex("#777777")
            width = 0.5
        }
    }
    layout {
        title = "Distribution of Winners by Successful Attempts"
        caption = "Data: Open IPF Meets 2025"
        size = 600 to 400
        style {
            global {
                text {
                    fontFamily = FontFamily.custom("Helvetica Neue")
                }
                plotCanvas {
                    title {
                        hJust = 0.5
                        margin = Margin(10.0)
                        fontSize = 16.0
                    }
                    caption {
                        hJust = 1.0
                        margin = Margin(10.0, 0.0, 0.0, 0.0)
                        fontSize = 12.0
                    }
                    margin = Margin(10.0, 30.0, 10.0, 10.0)
                }
            }
        }
    }
}

plotWinners
// Alternatively you can save your chart as an svg or png
//plotWinners.save("distribution-of-winners-custom-formatting.svg")
//plotWinners.save("distribution-of-winners-custom-formatting.png")

In [14]:
val allLiftersDataFrame = addNumberOfSuccessfulLifts(data.cast<LifterData>(), false)

In [15]:
allLiftersDataFrame

successfulLifts,count
3,277
4,1248
5,3798
6,7913
7,11571
8,12251
9,6873

In [16]:
val dfRatioWinners =
    dataFrameOf(
        winnersDataFrame.rename("count").into("winners").columns() +
                allLiftersDataFrame.select("count").rename("count").into("allLifters").columns()
    )
        .add("ratioWinners") {
            (column<Double>("winners").getValue(it) / column<Double>("allLifters").getValue(it)) * 100.0
        }

In [17]:
dfRatioWinners

successfulLifts,winners,allLifters,ratioWinners
3,35,277,"12,635379"
4,117,1248,"9,375000"
5,512,3798,"13,480779"
6,1284,7913,"16,226463"
7,2122,11571,"18,338951"
8,2546,12251,"20,781977"
9,1645,6873,"23,934235"

In [18]:
kandyConfig.themeApplied = false

val plotRatioWinners = dfRatioWinners.plot {

    bars {
        x(successfulLifts) {
            axis {
                name = "Successful Attempts"
                breaks(listOf(3, 4, 5, 6, 7, 8, 9), format = "d")
            }
        }
        y(ratioWinners) {
            axis.name = "Percentage"
            axis {
                breaks(listOf(5.0, 10.0, 15.0, 20.0, 25.0), format = "{.0f}%")
            }
        }
        fillColor(successfulLifts) {
            legend.type = LegendType.None
            scale = continuous(Color.hex("#dd4560")..Color.hex("#7e52ff"))
        }
        borderLine {
            color = Color.hex("#777777")
            width = 0.5
        }
    }
    layout {
        title = "Percentage of First Places by Successful Lifts"
        subtitle = "At least 3 lifters in Weight Class"
        caption = "Data: Open IPF meets 2025"
        size = 600 to 400
        style {
            global {
                text {
                    fontFamily = FontFamily.custom("Helvetica Neue")
                }
                plotCanvas {
                    title {
                        hJust = 0.5
                        margin = Margin(10.0)
                        fontSize = 14.0
                    }
                    subtitle {
                        hJust = 0.5
                        margin = Margin(5.0)
                        fontSize = 11.0
                    }
                    caption {
                        hJust = 1.0
                        margin = Margin(10.0, 0.0, 0.0, 0.0)
                    }
                    margin = Margin(10.0, 30.0, 10.0, 10.0)
                }
            }
        }
    }
}

plotRatioWinners
//plotRatioWinners.save("percetage-of-first-places.svg")

In [21]:
val plotGrid = plotGrid(
    listOf(plotWinners, plotRatioWinners),
    nCol = 2,
    widths = listOf(500.0, 500.0),
    heights =  listOf(400.0, 400.0)
)

plotGrid
//plotGrid.save("plot-grid-example.svg")

## Bonus analysis! Which was the most commonly missed lift?

In [91]:
val attemptColumns = listOf(
    LifterData::squat1kg, LifterData::squat2kg, LifterData::squat3kg,
    LifterData::bench1kg, LifterData::bench2kg, LifterData::bench3kg,
    LifterData::deadlift1kg, LifterData::deadlift2kg, LifterData::deadlift3kg
)

In [92]:
fun addWhichLiftsWereMissed(df: DataFrame<LifterData>): DataFrame<*> {

    return df.add("successfulLifts") {
        listOf(
            squat1kg, squat2kg, squat3kg,
            bench1kg, bench2kg, bench3kg,
            deadlift1kg, deadlift2kg, deadlift3kg
        ).count { it != null && it > 0.0 }
    }
        .filter { successfulLifts == 8 }
        .let { frame ->
            attemptColumns.map { lift ->
                val missedCount = frame[lift.name].cast<Double?>().count { it != null && it <= 0.0 }
                dataFrameOf("lift", "totalMissed")(lift.name, missedCount)
            }
                .concat()
        }
}

In [89]:
val missedLiftsDataFrame = addWhichLiftsWereMissed(data.cast<LifterData>())

In [90]:
missedLiftsDataFrame

lift,totalMissed
squat1kg,498
squat2kg,559
squat3kg,2042
bench1kg,345
bench2kg,677
bench3kg,4064
deadlift1kg,223
deadlift2kg,370
deadlift3kg,3346

In [77]:
val liftLabels = mapOf(
    "squat1kg" to "S1", "squat2kg" to "S2", "squat3kg" to "S3",
    "bench1kg" to "B1", "bench2kg" to "B2", "bench3kg" to "B3",
    "deadlift1kg" to "D1", "deadlift2kg" to "D2", "deadlift3kg" to "D3"
)

val plotMissedLifts = missedLiftsDataFrame
    .convert { lift }.with { liftLabels[it] ?: it }
    .plot {
    bars {
        x(lift)
        y(totalMissed) { axis.name = "count of attempts missed" }
        fillColor(totalMissed) {
            legend.type = LegendType.None
            scale = continuous(Color.hex("#dd4560")..Color.hex("#7e52ff"))
        }
        borderLine {
            color = Color.hex("#777777")
            width = 0.5
        }
    }
    layout {
        title = "Most Commonly Missed Lift - All lifters"
        caption = "Data: Open IPF meets 2025"
        size = 600 to 400
        xAxisLabel = "Lift"
        style {
            global {
                text {
                    fontFamily = FontFamily.custom("Helvetica Neue")
                }
                plotCanvas {
                    title {
                        hJust = 0.5
                        margin = Margin(10.0)
                        fontSize = 17.0
                    }
                    subtitle {
                        hJust = 0.5
                        margin = Margin(5.0)
                    }
                    caption {
                        hJust = 1.0
                        margin = Margin(10.0, 0.0, 0.0, 0.0)
                    }
                    margin = Margin(5.0, 30.0, 20.0, 5.0)
                }
            }
        }
    }
}
plotMissedLifts
//plotMissedLifts.save("most-commonly-missed-lifts-2015-2024.svg")

Answer: 3rd attempt bench press, it's not even close!